# Workflow name that appears in GitHub Actions UI
name: Lint

# Defines when this workflow will run
on:
  push:
    branches:
      - main  # Run on pushes to main branch
  pull_request:
    branches:
      - main  # Run on PRs targeting main branch

jobs:
  pre-commit:
    runs-on: ubuntu-latest  # Use latest Ubuntu runner

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Install uv package manager
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true  # Enable caching for faster installations

      # Set up Python using version specified in pyproject.toml
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      # Install project dependencies including dev dependencies
      - name: Install dependencies
        run: uv sync --all-extras --dev

      # Install pre-commit hooks
      - name: Install pre-commit hooks
        run: uv run pre-commit install

      # Run pre-commit on all files
      - name: Run pre-commit
        run: uv run pre-commit run --all-files
